[build]
  publish = "."
  
[[redirects]]
  from = "http://c-fund.org/*"
  to = "https://c-fund.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.c-fund.org/*"
  to = "https://c-fund.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.c-fund.org/*"
  to = "https://c-fund.org/:splat"
  status = 301
  force = true
